### PR TITLE
Issue #44

### PR DESCRIPTION
**Pull request by mcmartins**

### CODE REVIEW

**Comment by mcmartins** [comment]
@zerline , I'll be reviewing it next week, thanks!

**Comment by mcmartins** [comment]
I'm not sure about the changes on the webpack configuration. No sure if that has any impact with extension installation. I'm tempted to just replicate the changes in the other files.

**Comment by zerline** [comment]
@mcmartins I'll have a look tonight or tomorrow. Feel free to suggest changes, I'll test them as well :)

**Comment by zerline** [comment]
> @mcmartins I'll have a look tonight or tomorrow. Feel free to suggest changes, I'll test them as well :)



> I'm not sure about the changes on the webpack configuration. No sure if that has any impact with extension installation. I'm tempted to just replicate the changes in the other files.

Do you not think useful to update the syntax? It is now much clearer. Of course, it also has to _work_. I'll give it some more time.

**Comment by zerline** [comment]
Hi Manuel

I've run this building again. I still get an error but it might be related to my own environment.

Regards,

**Comment by zerline** [comment]
> Hi Manuel
> 
> I've run this building again. I still get an error but it might be related to my own environment.
> 
> Regards,

I constantly get this error (below, for ~20 files in francy dependencies)

Yet it seems to work .. Need to check.
```
ERROR in ./node_modules/francy-renderer-vis/src/canvas.js 20:2
    Module parse failed: Unexpected character '@' (20:2)
    You may need an appropriate loader to handle this file type.
    |   }
    | 
    >   @Decorators.Data.requires('canvas')
    |   async render() {
    |     const canvasId = `Canvas-${this.data.canvas.id}`;
     @ ./node_modules/francy-renderer-vis/index.js 1:0-34 9:10-16
     @ multi babel-polyfill francy-renderer-vis
```

**Comment by mcmartins** [comment]
Hi @zerline, that error is because webpack cannot find the Babel modules required for the transpiration of decorators etc... you need the module.rules.loaders on the lab extension as well.
Cheers.

**Comment by zerline** [comment]
> Hi @zerline, that error is because webpack cannot find the Babel modules required for the transpiration of decorators etc... you need the module.rules.loaders on the lab extension as well.

Hi @mcmartins 
Yet `@babel/plugin-proposal-decorators` is there in `package.json` + in `webpack.config.js`. What else should be done? 

> Cheers.

Thanks, same to you

**Comment by mcmartins** [comment]
Many things changed since this, and I tried to address everything on #88

**Pull request closed without merging**
