### PR TITLE
Switch from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
This applies our standard setup for GAP packages to use GitHub Actions. 

It passes in my fork, e.g. https://github.com/alex-konovalov/francy/actions/runs/1098671318

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@mcmartins do you have any objections for me to merge this?

**Comment by mcmartins** [comment]
The problem I see is that on TravisCI we were running a few scripts to handle the release procedure, and with github actions they seem to be missing.

```
...
before_script:
  - scripts/prepare.sh
script:
  - scripts/tests.sh
after_success:
  - scripts/coverage.sh

deploy:
  provider: script
  script: bash scripts/release.sh
  skip_cleanup: true
  on:
    tags: true
...
```

I guess this works fines for GAP packages but with Francy there are a few more things being built, including `pip` and `npm` packages. Those will need to be included as well, or split into independent modules.

**Comment by olexandr-konovalov** [comment]
@mcmartins ah, thanks for pointing out! I will look how to incorporate those steps by adjusting the basic setup for GAP packages.

**Comment by fingolfin** [comment]
I've taken the liberty of rebasing this PR and then adding some tweaks to it (in a separate commit, to make visible what I changed; of course it could be squashed when merged).

Note that it should be absolutely possibly to accommodate all the extra steps `francy` needs with GH actions. We are also using GH actions to create GAP releases. I am not sure when Travis runs those "deploy" jobs, but in any case it'd be trivial to have that `scripts/release.sh` script run either via a manual trigger (i.e. "press a button on GitHub to run it") or in response to a tag being created, or something else.

Of course changes will be needed:
- it hardcodes Python 3.6, should use the Python3 that is installed by whatever Ubuntu version is being used right now (by default: 20.04, but one can also use 22.04 or, until early 2023, also 18.04)
   - if for some reason it really is necessary to use an old python, of course there also ways to do that, but I hope not...?
- there are several premade GH actions (think of little macros/scripts that you can easily invoke from your own GH workflows) which create new GH releases: you just point it at the commit or tag, give it a list of files, possible some extra data, and done. So that's easy
- I never used `npm` but I don't see a problem there; of course `NPM_TOKEN` must be set, but GH Actions of course have easy to use method to provide such "secrets" to scripts.

If you, @mcmartins  ever want to have a chat about what is possible and how to achieve it, I'd be happy to help.

**Comment by fingolfin** [comment]
@mcmartins this PR has conflicts because it was rebased on `master`, but targets `develop`. I can of course rebase it on `develop`, but the easiest option would be to rebase `develop` on `master` (or merge `master` into `develop, if you prefer that)

**Comment by mcmartins** [comment]
Thanks for this!

My plan is to ditch any releases to NPM and possibly to pypi.org, making the package more similar to the jupyterkernel, where one just goes into the pkg directory and does pip install.

As for the conflicts part, develop is work in progress and not really working at the moment, so probably the merge of master into develop is better. Feel free to make any changes that you feel are a great improve to the package.

**Comment by fingolfin** [comment]
I have simply re-targeted this PR to point at `master`.

**Pull request closed without merging**
