### PR TITLE
Switch to GH Actions (alternate version of PR #68)

### PR DESCRIPTION
**Pull request by fingolfin**
This differs from PR #68 in that the branch lives in this repo, not a fork, which I *think* means we'll get to see test runs of it before actually merging it... not sure if I am right, we'll see

Closes #68

### CODE REVIEW

**Review by olexandr-konovalov — APPROVED** [review]
I think we should merge this. From the discussion in #68 seems like you addressed all by now, and even if some things left out, then subsequent polishing is easier with functional CI. Do you agree, @mcmartins ?

**Review by mcmartins — APPROVED** [review]

**Comment by olexandr-konovalov** [comment]
Very good! Will leave to @fingolfin to merge (do you want to squash commits or not)

**Comment by mcmartins** [comment]
Yes, this is fine to be merged with Squashed commits. I’m waiting for https://github.com/magjac/d3-graphviz/pull/242/files/e796f9ad6858b64e055e7ce60631b3fb650259a9..e7509e66f2088465a77d12f38d377febd03cfa32 to be merged so I can upgrade all dependencies (mainly because d3 is used across the ja packages) and release version 2 of francy.

**Comment by fingolfin** [comment]
I've pushed a minor update. Assuming CI still passes, let's merge (squash, whatever) it

**Comment by olexandr-konovalov** [comment]
GAP 4.11 test fails
```
#I  json: PackageAvailabilityInfo for version 2.1.1
#I        (required: >= 2.0.0)
#I  (unknown package): PackageAvailabilityInfo: required GAP version (>= 4.12) does not fitjson
#I  json: PackageAvailabilityInfo: no installed version fits
```

**Comment by fingolfin** [comment]
The problem is within GAP's stable-4.11 branch, which still downloads the "latest" set of GAP packages, which by now includes packages that require GAP 4.12. I'll fix it there.

**Pull request merged**
